# data-raw/build_bcfishpass_rules_yaml.R
#
# Generate a rules YAML that matches bcfishpass v0.5.0 exactly.
# This is NOT our NGE defaults (those are in build_habitat_rules_yaml.R).
# This is for the comparison script (compare_adms.R) to validate that
# fresh+link can reproduce bcfishpass outputs.
#
# Key differences from NGE defaults:
#   - Spawning: edge_types_explicit [1000, 1100, 2000, 2300] (excludes 1050/1150)
#   - waterbody_type=R: thresholds false (bcfishpass skips cw_min on river polygons)
#   - Wetland-flow rear carve-out: CO only (not all species)
#   - Lake rearing: SK and KO only (not BT/CH/ST etc)
#   - BT rear: no edge filter at all (bcfishpass has none)
#
# Usage:
#   source("data-raw/build_bcfishpass_rules_yaml.R")

stopifnot(requireNamespace("yaml", quietly = TRUE))

output_path <- "inst/extdata/parameters_habitat_rules_bcfishpass.yaml"

# bcfishpass v0.5.0 species classified in ADMS: BT, CH, CO, SK
# (CM, PK have spawning but no rearing; ST, WCT not present in ADMS)
# Build for ALL species bcfishpass models, not just ADMS.

# bcfishpass v0.5.0 spawning pattern (all species except SK):
#   edge_type IN (1000, 1100, 2000, 2300) — excludes wetland-flow (1050/1150)
#   OR waterbody_type = 'R' — river polygons skip cw_min check
#   gradient <= spawn_gradient_max
#   channel_width > spawn_channel_width_min (skipped for waterbody_type=R)
#   channel_width <= spawn_channel_width_max
#   access barrier check (handled by fresh gate/label_block, not rules)

# Common spawning rules (all species)
spawn_stream <- list(
  edge_types_explicit = c(1000L, 1100L, 2000L, 2300L)
  # thresholds inherited from CSV (gradient + channel_width applied)
)
spawn_river <- list(
  waterbody_type = "R",
  # bcfishpass skips cw_min for R segments but still checks gradient.
  # fresh 0.12.1 supports per-rule threshold overrides (fresh#116):
  # set channel_width to [0, 9999] to skip the minimum, inherit gradient.
  channel_width = c(0, 9999)
)

# --- Species rules ---

rules <- list(
  BT = list(
    spawn = list(spawn_stream, spawn_river),
    # BT rearing in bcfishpass: no edge_type filter. Any segment meeting
    # gradient <= 10.49% and cw >= 1.5 AND connected to spawning.
    # Express as a single rule with thresholds inherited, no edge filter.
    rear = list(
      list()  # empty rule = no predicates = all segments, thresholds inherited
    )
  ),

  CH = list(
    spawn = list(spawn_stream, spawn_river),
    # CH rearing: edge_type IN (1000, 1100, 2000, 2300) only — no wetland/lake
    rear = list(
      list(edge_types_explicit = c(1000L, 1100L, 2000L, 2300L))
    )
  ),

  CM = list(
    spawn = list(spawn_stream, spawn_river),
    # CM: no freshwater rearing
    rear = list()
  ),

  CO = list(
    spawn = list(spawn_stream, spawn_river),
    # CO rearing: streams/canals + wetland-flow carve-out (1050/1150 no thresholds)
    rear = list(
      list(edge_types_explicit = c(1000L, 1100L, 2000L, 2300L)),
      list(edge_types_explicit = c(1050L, 1150L), thresholds = FALSE)
    )
  ),

  PK = list(
    spawn = list(spawn_stream, spawn_river),
    # PK: no freshwater rearing
    rear = list()
  ),

  SK = list(
    spawn = list(spawn_stream, spawn_river),
    # SK rearing: lake-only (rear_lake_ha_min = 200)
    rear = list(
      list(waterbody_type = "L", lake_ha_min = 200)
    )
  ),

  ST = list(
    spawn = list(spawn_stream, spawn_river),
    # ST rearing: same edge_types as spawning
    rear = list(
      list(edge_types_explicit = c(1000L, 1100L, 2000L, 2300L))
    )
  ),

  WCT = list(
    spawn = list(spawn_stream, spawn_river),
    # WCT rearing: same edge_types as spawning
    rear = list(
      list(edge_types_explicit = c(1000L, 1100L, 2000L, 2300L))
    )
  )
)

# --- Write YAML ---

header <- c(
  "# bcfishpass v0.5.0 matching rules",
  "# Generated by data-raw/build_bcfishpass_rules_yaml.R",
  paste0("# Generated: ", format(Sys.Date(), "%Y-%m-%d")),
  "#",
  "# These rules replicate bcfishpass v0.5.0 habitat_linear SQL exactly.",
  "# For NGE saner defaults, use parameters_habitat_rules.yaml instead.",
  "#",
  "# Key bcfishpass conventions replicated here:",
  "#   - Spawning only on edge_type 1000/1100/2000/2300 (excludes 1050/1150 wetland-flow)",
  "#   - waterbody_type=R segments skip channel_width_min check (thresholds: false)",
  "#   - CO rearing includes wetland-flow 1050/1150 with no threshold checks",

  "#   - SK/KO rearing is lake-only (lake_ha_min: 200)",
  "#   - BT rearing has no edge_type filter",
  "#   - CH/ST/WCT rearing restricted to 1000/1100/2000/2300",
  "#   - CM/PK have no freshwater rearing",
  ""
)

yaml_body <- yaml::as.yaml(rules,
  indent = 2,
  handlers = list(
    logical = function(x) {
      v <- ifelse(x, "true", "false")
      class(v) <- "verbatim"
      v
    }
  )
)

writeLines(c(header, yaml_body), output_path)
message("Wrote ", output_path)
message("Species: ", paste(names(rules), collapse = ", "))
